name: geneval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  #- pytorch=2.1
  - torchvision
  - pip:
    - open-clip-torch
    - clip-benchmark
    - openmim
    - einops
    - lightning
    - diffusers
    - transformers
    - tomli
    - platformdirs
    - setuptools
    - numpy<2

# Then need to 
#
# mim install mmengine mmcv-full==1.7.2
# git clone https://github.com/open-mmlab/mmdetection.git
# git checkout 2.x
# cd mmdetection
# pip install -e .
#
# Note: mim install must be done before mmdetection install
# mmcv-full requirement could probably be relaxed to <1.8
# unclear about pytorch version dependency. Works with python=3.11
